export const BRAND_CATEGORY_MAP = {
  WORKER: 'Ferramentas e Equipamentos',
  AMATOOLS: 'Ferramentas e Medicao',
  KRONA: 'Hidraulica e Saneamento',
  JOMARCA: 'Ferragens e Seguranca',
  MAKITA: 'Ferramentas e Equipamentos',
  LOTUS: 'Ferramentas e Equipamentos',
  VONDER: 'Ferramentas e Equipamentos',
  TRAMONTINA: 'Ferramentas e Utilidades',
  SATA: 'Ferramentas e Equipamentos',
  CORTAG: 'Ferramentas e Acabamento',
  'BESTFER BF': 'Ferramentas e Utilidades',
  DETONI: 'Ferragens e Fixacao',
  IRWIN: 'Ferramentas e Equipamentos',
  STAM: 'Ferragens e Seguranca',
  BRACOL: 'EPIs e Seguranca',
  SILVANA: 'Ferragens e Seguranca',
  ATLAS: 'Tintas e Pintura',
  COLLINS: 'Ferramentas e Quimicos',
  CARROCINHA: 'Movimentacao e Logistica',
  COZIMAX: 'Cozinha e Organizacao',
  JOCEC: 'Ferragens e Fixacao',
  ANJO: 'Tintas e Pintura',
  CARBOGRAFITE: 'Solda e Abrasivos',
  WBR: 'Ferragens e Fixacao',
  MARCON: 'Ferramentas e Construcao',
  KALA: 'Ferramentas e Equipamentos',
  MARLUVAS: 'EPIs e Seguranca',
  ORBI: 'Quimicos e Lubrificantes',
  CINFER: 'Fixacao e Parafusos',
  COMPEL: 'Eletrica e Iluminacao',
  SUVINIL: 'Tintas e Pintura',
  KALIPSO: 'EPIs e Seguranca',
  SOLVENTEX: 'Tintas e Solventes',
  GERDAU: 'Acos e Metalurgia',
  DENVER: 'Impermeabilizantes e Quimicos',
  MAYLE: 'Fixacao e Ferragens',
  PLUZIE: 'Eletrica e Iluminacao',
  QUARTZOLIT: 'Argamassas e Construcao',
  '3F': 'Ferragens e Fixacao',
  ANFIX: 'Fixacao e Parafusos',
  CISER: 'Fixacao e Parafusos',
  ASTRA: 'Hidraulica e Banheiro',
  ACQUABIOS: 'Hidraulica e Filtracao',
  'HM RUBBER': 'Vedacao e Borrachas',
  PADO: 'Ferragens e Seguranca',
  BRONZEARTE: 'Eletrica e Iluminacao',
  STARRETT: 'Ferramentas e Medicao',
  TOYAMA: 'Motores, Bombas e Jardim',
  LOYAL: 'Ferragens e Fixacao',
  BELGO: 'Acos e Metalurgia',
  BELZER: 'Ferramentas e Equipamentos',
  BRAVON: 'Ferramentas e Equipamentos',
  MTX: 'Ferramentas e Equipamentos',
  RAMASSOL: 'Argamassas e Construcao',
  COLORGIN: 'Tintas e Pintura',
  COMEP: 'Eletrica e Iluminacao',
  EINHELL: 'Ferramentas e Equipamentos',
  GLOBALPLAST: 'Hidraulica e Plasticos',
  BRASKORT: 'EPIs e Seguranca',
  GSP: 'Fixacao e Ferragens',
  BOSCH: 'Ferramentas e Equipamentos',
  BOXER: 'Ferramentas e Equipamentos',
  'GRUPO ELITE': 'Ferragens e Fixacao',
  INCA: 'Tintas e Pintura',
  TRON: 'Eletrica e Iluminacao',
  DIVERSAS: 'Outras marcas',
  MENEGOTTI: 'Ferramentas e Construcao',
  PRESSURE: 'Lavadoras e Bombas',
  'RED DIAMOND': 'Solda e Abrasivos',
  ACEROSID: 'Acos e Metalurgia',
  CARNEIRO: 'Fixacao e Ferragens',
  DURIN: 'Hidraulica e Saneamento',
  INOX: 'Acos e Metalurgia',
  ALIANCA: 'Ferragens e Seguranca',
  HIDRACOR: 'Tintas e Pintura',
  INVICTA: 'Utilidades e Organizacao',
  SCHULZ: 'Compressores e Ar',
  DPLASTIC: 'Hidraulica e Plasticos',
  LUFKIN: 'Ferramentas e Medicao',
  TAMBASA: 'Ferragens e Utilidades',
  MATSUYAMA: 'Motores, Bombas e Jardim',
  PLASTMAN: 'Hidraulica e Plasticos',
  SR: 'Ferragens e Fixacao',
  'VONDER PLUS': 'Ferramentas e Equipamentos',
  BRASCOLA: 'Quimicos e Adesivos',
  CSM: 'Ferramentas e Construcao',
  FORCE: 'Ferramentas e Equipamentos',
  GLASU: 'Tintas e Solventes',
  'K&F': 'Ferragens e Fixacao',
  MERKEL: 'Solda e Abrasivos',
  SKILL: 'Ferramentas e Equipamentos',
  WEG: 'Eletrica e Motores',
  AVANTI: 'Ferramentas e Equipamentos',
  KAEF: 'EPIs e Seguranca',
  TEKBOND: 'Quimicos e Adesivos',
  TITANIUM: 'Ferramentas e Solda',
  '3M': 'Quimicos e Adesivos',
  NOVE54: 'Ferramentas e Utilidades',
  ANAUGER: 'Bombas e Saneamento',
  'M&M': 'Ferragens e Fixacao',
  RIOMAR: 'Ferragens e Fixacao',
  'SANTA BARBARA': 'Acos e Metalurgia',
  ATLANTICORDAS: 'Cordas e Movimentacao',
  BRASCAMP: 'EPIs e Seguranca',
  COBIX: 'Solda e Abrasivos',
  COLEMAN: 'Utilidades e Camping',
  CORALIT: 'Tintas e Pintura',
  DOVALE: 'Utilidades e Organizacao',
  ETERNIT: 'Coberturas e Construcao',
  H7: 'Ferramentas e Equipamentos',
  GB: 'Ferragens e Fixacao',
  MAGMA: 'Solda e Abrasivos',
  NEGRAO: 'Acos e Metalurgia',
  RESOL: 'Utilidades e Limpeza',
  UTP: 'Solda e Abrasivos',
  AGL: 'Ferragens e Seguranca',
  AJAX: 'Limpeza e Quimicos',
  'ARCELOR MITTAL': 'Acos e Metalurgia',
  ESAB: 'Solda e Abrasivos',
  FERRONORTE: 'Acos e Metalurgia',
  FORTLEV: 'Hidraulica e Saneamento',
  IQUINE: 'Tintas e Pintura',
  'NAKA (TAMBASA)': 'Ferragens e Utilidades',
  PRENSAL: 'Ferragens e Fixacao',
  SINOBRAS: 'Acos e Metalurgia',
  WELLER: 'Solda e Ferramentas',
  ZANEL: 'EPIs e Seguranca',
  'AMAZON ACO': 'Acos e Metalurgia',
  ARPREX: 'Tintas e Solventes',
  CASCOLA: 'Quimicos e Adesivos',
  CORNETA: 'Ferramentas e Utilidades',
  MAXLONA: 'Coberturas e Lonas',
  NICHOLSON: 'Ferramentas e Equipamentos',
  PITBULL: 'Ferramentas e Equipamentos',
  REMOX: 'Quimicos e Lubrificantes',
  SOMAR: 'Ferragens e Fixacao',
  START: 'Limpeza e Quimicos',
  TF7: 'Quimicos e Lubrificantes',
  THINSOL: 'Tintas e Solventes',
  'TV IMPERIAL': 'Coberturas e Construcao',
  VOESTALPINE: 'Acos e Metalurgia',
  AXT: 'Ferragens e Fixacao',
  BOTAFOGO: 'Utilidades e Organizacao',
  ELITE: 'Ferragens e Fixacao',
  IDERE: 'Ferragens e Fixacao',
  'JOAO DE BARRO': 'Construcao e Coberturas',
  LYNUS: 'Ferramentas e Equipamentos',
  METALCAVA: 'Acos e Metalurgia',
  MOMFORT: 'Utilidades e Organizacao',
  MOTOMIL: 'Compressores e Motores',
  'MULTI-FIX': 'Fixacao e Parafusos',
  ROADKIN: 'EPIs e Seguranca',
  SERV: 'Ferragens e Fixacao',
  STELS: 'Ferramentas e Equipamentos',
  TENACI: 'Quimicos e Adesivos',
}

export function obterCategoriaMarcaPorMapa(marca) {
  if (!marca) return null

  return BRAND_CATEGORY_MAP[String(marca).trim().toUpperCase()] || null
}
