export const ERP_GRUPO_NOMES = {
  1: 'ACABAMENTO',
  2: 'ACESSORIOS',
  3: 'ARAME',
  4: 'ARGAMASSA',
  5: 'BARRA',
  6: 'BARRAS',
  7: 'BARRINHA',
  8: 'BOBINA',
  9: 'BOTA',
  10: 'BROCA',
  11: 'CADEADO',
  12: 'CAIXA DE CORREIOS',
  13: 'CAIXA TERMICA',
  14: 'CAMPING',
  15: 'CANTONEIRA',
  16: 'CAPOTE',
  17: 'CARRINHO DE CARGA',
  18: 'CHAPA GALVANIZADA',
  19: 'CHAPA PRETA',
  20: 'CHAPAS',
  21: 'CHAVE',
  22: 'CHUMBADOR',
  23: 'CILINDRO',
  24: 'CLASSE',
  25: 'COLANTES',
  26: 'CONSTRUÇÃO SECA',
  27: 'CORDA',
  28: 'CORRENTE',
  29: 'DISCOS',
  30: 'ABRASIVOS',
  31: 'DIVERSOS',
  32: 'DOBRADIÇA',
  33: 'ELETRODO',
  34: 'EPI',
  35: 'EQUIPAMENTO PINTURA',
  36: 'EQUIPAMENTOS',
  37: 'ESGOTO',
  38: 'ESQUADRIAS',
  39: 'ESTRIBOS',
  40: 'FECHADURA',
  41: 'FECHADURAS',
  42: 'FERRAMENTAS',
  43: 'FERRAMENTAS AGRICOLAS',
  44: 'FERRAMENTAS ELETRICAS',
  45: 'FERRAMENTAS MANUAIS',
  46: 'FERROLHO',
  47: 'FITA',
  48: 'FOGÃO',
  49: 'GONZO',
  50: 'GUIA',
  51: 'HIDRAULICA',
  52: 'IMPERMEABILIZANTE',
  53: 'INATIVO',
  54: 'JARDINAGEM',
  55: 'LAMPADAS',
  56: 'LIXEIRAS',
  57: 'MANGUEIRAS',
  58: 'MAQUINAS',
  59: 'MATERIAL ELÉTRICO',
  60: 'METALON',
  61: 'MIX FERRONORTE',
  62: 'NÃO ESPECIFICADO',
  63: 'OUTROS',
  64: 'PARAFUSOS',
  65: 'PERFIL',
  66: 'PLASTICOS DIVERSOS',
  67: 'PONTEIRA',
  68: 'PUXADOR',
  69: 'QUIMICOS',
  70: 'RODIZIO',
  71: 'ROLDANAS',
  72: 'SERVIÇO',
  73: 'SPRAY',
  74: 'STAM',
  75: 'SUVINIL ESM',
  76: 'TAMBOR',
  77: 'TAMBOR COM MOLA',
  78: 'TELA PRATICA',
  79: 'TELAS',
  80: 'TELHA',
  81: 'TELHAS',
  82: 'THINER',
  83: 'TINTAS/SOLVENTES',
  84: 'TUBO',
  85: 'TUBOS',
  86: 'UCD',
  87: 'VERGALHÃO',
  88: 'BEBEDOUROS',
  89: 'BOMBONIERE',
  90: 'BONIFICAÇÃO',
  91: 'CABOS DE AÇO',
  92: 'CARROCINHA',
  93: 'COMPRESSORES',
  94: 'CONSUMO',
  95: 'ENTREGAS',
  96: 'ESCRITORIO',
  97: 'EXPOSITORES',
  98: 'PORTAS/JANELAS',
  99: 'SALAO VENDAS',
  100: 'CONEXÕES',
  101: 'ESCADAS',
  102: 'EQUIPAMENTOS SOLDA',
  103: 'FERRO N ESQUADRIAS',
  104: 'CHURRASQUEIRA',
  105: 'PREGOS',
  9999: 'GERAL',
}

const NOMES_COMERCIAIS = {
  ACESSORIOS: 'Acessórios',
  HIDRAULICA: 'Hidráulica',
  LAMPADAS: 'Lâmpadas',
  MAQUINAS: 'Máquinas',
  QUIMICOS: 'Químicos',
  RODIZIO: 'Rodízio',
  'PLASTICOS DIVERSOS': 'Plásticos diversos',
  'FERRAMENTAS AGRICOLAS': 'Ferramentas agrícolas',
  'FERRAMENTAS ELETRICAS': 'Ferramentas elétricas',
  'FERRAMENTAS MANUAIS': 'Ferramentas manuais',
  'CAIXA TERMICA': 'Caixa térmica',
  'TELA PRATICA': 'Tela prática',
  'CABOS DE AÇO': 'Cabos de aço',
  'PORTAS/JANELAS': 'Portas e janelas',
  'MATERIAL ELÉTRICO': 'Material elétrico',
  'EQUIPAMENTOS SOLDA': 'Equipamentos de solda',
  'TINTAS/SOLVENTES': 'Tintas e solventes',
  'NÃO ESPECIFICADO': 'Não especificado',
}

export function formatarNomeGrupoErp(nome) {
  const valor = String(nome || '').trim()
  if (!valor) return ''
  const upper = valor.toUpperCase()
  if (NOMES_COMERCIAIS[upper]) return NOMES_COMERCIAIS[upper]

  return valor
    .toLocaleLowerCase('pt-BR')
    .replace(/(^|\s|\/|-)([a-zà-ú])/g, (_, prefixo, letra) => `${prefixo}${letra.toLocaleUpperCase('pt-BR')}`)
}

export function obterNomeGrupoErp(produto) {
  const nomeApi = produto?.grupo_nome || produto?.nome_grupo || produto?.grupo_descricao
  if (nomeApi) return formatarNomeGrupoErp(nomeApi)

  const grupo = Number(produto?.grupo || 0)
  return formatarNomeGrupoErp(ERP_GRUPO_NOMES[grupo] || '')
}
